/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { Catalog } from './src/main/ets/interface/Catalog';
export {
  CatalogItem,
  ChangeReason,
  ComponentBuilder,
  ComponentTheme,
  CustomComponentAttribute
} from './src/main/ets/interface/CatalogItem';
export {
  Capabilities,
  CapabilityManifest
} from './src/main/ets/interface/Capabilities';
export {
  ClientFunction,
  FunctionCall,
  FunctionContext,
  FunctionErrorReporter
} from './src/main/ets/interface/ClientFunction';
export {
  DynamicValueResolver,
  ResolveValueCallback
} from './src/main/ets/interface/DynamicValueResolver';
export {
  CatalogFactory,
  SurfaceControllerFactory
} from './src/main/ets/interface/Factories';
export {
  MultiSurfaceController
} from './src/main/ets/interface/MultiSurfaceController';
export { PromptBuilder } from './src/main/ets/interface/PromptBuilder';
export {
  ActionReceiver,
  ErrorCallback,
  SchemaWarningInfo,
  SurfaceController,
  SurfaceControllerOption,
  SurfaceEventCallback
} from './src/main/ets/interface/SurfaceController';
export {
  SurfaceErrorCode,
  SurfaceEventType
} from './src/main/ets/interface/Types';
export {
  BASIC_CATALOG_PROTOCOL_VERSION_V09,
  EXTENDED_CATALOG_PROTOCOL_VERSION_V100
} from './src/main/ets/interface/Version';
export {
  A2UIValueType,
  Breakpoint,
  SchemaProvider,
  ThemeMode
} from './src/main/ets/interface/Types';
export { UIRendererComponent } from './src/main/ets/interface/UIRendererComponent';
